import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ReactQueryProvider from "@/query/ReactQueryProvider";
import { AuthContext } from "@/context/AuthContext";
import Footer from "@/components/Footer";
import RelatedProducts from "@/components/RelatedProducts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Green Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-[120px]`}
      >
        <ReactQueryProvider>
          <AuthContext>
            <Header />
            {children}
            <Footer/>
          </AuthContext>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
